version: "3.9"
services:
 timesheet:
   build: .
   ports:
     - "8082:8082"
   image: "timesheet-image"
   links:
    - mysql
   depends_on:
     - mysql

 mysql:
   container_name: mysql
   ports:
    - "3306:3306"
   image: "mysql"   
      
