version: "3.9"
services:
 timesheet:
   build: .
   ports:
     - "8082:8082"
   image: "timesheet-image"
   links:
    - mysql
   depends_on:
     - mysql
   environment:
     - spring.datasource.url=jdbc:mysql://mysql:3307/timesheet-spring?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
     

 mysql:
   container_name: mysql
   ports:
    - "3307:3306"
   image: "mysql"   
      
